# La compréhension de liste

## Fonction enumerate()

In [1]:
students = ["Anna", "Martin", "Bob", "Eric", "Elise"]
ages = [16, 15, 18, 20, 20]

In [2]:
for student in students:
    print("Etudiant")
    print(student)
    print("Age")

Etudiant
Anna
Age
Etudiant
Martin
Age
Etudiant
Bob
Age
Etudiant
Eric
Age
Etudiant
Elise
Age

In [3]:
for i, student in enumerate(students):
    print("Index Etudiant")
    print(i)
    print("Etudiant")
    print(student)

Index Etudiant
0
Etudiant
Anna
Index Etudiant
1
Etudiant
Martin
Index Etudiant
2
Etudiant
Bob
Index Etudiant
3
Etudiant
Eric
Index Etudiant
4
Etudiant
Elise

In [4]:
for i, student in enumerate(students):
    print("Index Etudiant")
    print(i)
    print("Etudiant")
    print(student)
    print("Age")
    print(ages[i])

Index Etudiant
0
Etudiant
Anna
Age
16
Index Etudiant
1
Etudiant
Martin
Age
15
Index Etudiant
2
Etudiant
Bob
Age
18
Index Etudiant
3
Etudiant
Eric
Age
20
Index Etudiant
4
Etudiant
Elise
Age
20

In [5]:
cars = [["Noir", "Peugeot", "308"], ["Blanche", "Audi", "A4"]]
price = [23000, 49000]

In [6]:
for i, car in enumerate(cars):
    car.append(price[i])

In [7]:
print(cars)

[['Noir', 'Peugeot', '308', 23000], ['Blanche', 'Audi', 'A4', 49000]]

## Compréhension de liste

In [8]:
animals = ["Chien", "Tigre", "Lion", "Vache", "Panda"]

animal_lengths = []
for animal in animals:
    animal_lengths.append(len(animal))
    
print(animal_lengths)

[5, 5, 4, 5, 5]

In [9]:
animal_lengths_2 = [len(animal) for animal in animals]
print(animal_lengths_2)

[5, 5, 4, 5, 5]

In [10]:
prices = [10, 45, 156, 7800]
prices_doubled = [price * 2 for price in prices]
print(prices_doubled)

[20, 90, 312, 15600]

### Training

In [11]:
import csv
f = open("legislators.csv")
legislators = list(csv.reader(f))

birth_year = []

for row in legislators:
    birthday = row[2]
    birth_year = birthday.split("-")[0]
    try:
        birth_year = int(birth_year)
    except Exception:
        birth_year = 0
    row.append(birth_year) #ajout d'une nouvelle colonne

legislators[0][7] = "birth_year" #ajout d'un nouvelle entête de colonne index0 colonne7

print(legislators[0:10])

[['last_name', 'first_name', 'birthday', 'gender', 'type', 'state', 'party', 'birth_year'], ['Bassett', 'Richard', '1745-04-02', 'M', 'sen', 'DE', 'Anti-Administration', 1745], ['Bland', 'Theodorick', '1742-03-21', '', 'rep', 'VA', '', 1742], ['Burke', 'Aedanus', '1743-06-16', '', 'rep', 'SC', '', 1743], ['Carroll', 'Daniel', '1730-07-22', 'M', 'rep', 'MD', '', 1730], ['Clymer', 'George', '1739-03-16', 'M', 'rep', 'PA', '', 1739], ['Contee', 'Benjamin', '', 'M', 'rep', 'MD', '', 0], ['Dalton', 'Tristram', '1738-05-28', '', 'sen', 'MA', 'Pro-Administration', 1738], ['Elmer', 'Jonathan', '1745-11-29', 'M', 'sen', 'NJ', 'Pro-Administration', 1745], ['Few', 'William', '1748-06-08', 'M', 'sen', 'GA', 'Anti-Administration', 1748]]

In [12]:
name_counts = {}

for row in legislators:
    gender = row[3]
    year = row[7]
    
    if gender == "F" and year > 1950:
        name = row[1]
        if name in name_counts:
            name_counts[name] += 1
        else:
            name_counts[name] = 1

print(name_counts)

{'Enid': 1, 'Lynn': 1, 'Karen': 1, 'Denise': 1, 'Katherine': 1, 'Melissa': 2, 'Blanche': 1, 'Cynthia': 1, 'Shelley': 2, 'Nancy': 1, 'Deborah': 2, 'Heather': 1, 'Kathleen': 2, 'Mary': 2, 'Stephanie': 1, 'Betsy': 1, 'Hilda': 1, 'Ellen': 1, 'Gabrielle': 1, 'Sandy': 1, 'Ann Marie': 1, 'Nan': 1, 'Laura': 1, 'Jean': 1, 'Betty': 1}

In [13]:
values = [5, 70, 110]
max_value = 0
for i in values:
    if i > max_value:
        max_value = i

print(max_value)

110

In [14]:
values = [-5, -70, -110]
max_value = 0
for i in values:
    if i > max_value:
        max_value = i

print(max_value)

0

In [15]:
values = [-5, -70, -110]
max_value = None
for i in values:
    if max_value is None or i > max_value:
        max_value = i

print(max_value)

-5

In [16]:
a = None
a > 10

TypeError: '>' not supported between instances of 'NoneType' and 'int'

### Training

In [ ]:
values = [None, 1, 45, None, 75]

check = [x is not None and x >30 for x in values]
print(check)

## Application: prénoms féminins les plus fréquents

### Training

In [ ]:
max_value = None

for k in name_counts:
    count = name_counts[k]
    if max_value is None or count > max_value:
        max_value = count

print(max_value)

## La méthode items()

In [ ]:
fruits = {
    "banane":9,
    "orange":15,
    "kiwi":4
}

In [ ]:
for fruit, number in fruits.items():
    print(fruit)
    print(number)

## Trouver les prénoms les plus fréquents

In [24]:
top_female_names = []
top_female_names = [k for k, v in name_counts.items() if v == 2]
print(top_female_names)

['Melissa', 'Shelley', 'Deborah', 'Kathleen', 'Mary']

### Training

In [18]:
male_name_counts = {}

for row in legislators:
    gender = row[3]
    year = row[7]
    
    if gender == "M" and year > 1940:
        name = row[1]
        if name in male_name_counts:
            male_name_counts[name] += 1
        else:
            male_name_counts[name] = 1

print(male_name_counts)

{'Michael': 20, 'David': 24, 'James': 31, 'John': 35, 'Paul': 6, 'Joseph': 5, 'Donald': 4, 'William': 21, 'Thomas': 18, 'Anthony': 3, 'Charles': 17, 'Raymond': 2, 'Fred': 2, 'Robert': 24, 'Kenneth': 1, 'Mark': 9, 'Harold': 3, 'Daniel': 4, 'Patrick': 3, 'Richard': 9, 'George': 6, 'Peter': 9, 'Chester': 1, 'Harry': 2, 'Earl': 3, 'Edward': 3, 'Albert': 3, 'Carl': 1, 'Martin': 3, 'Lawrence': 1, 'Milton': 1, 'Samuel': 2, 'Frederick': 2, 'Timothy': 3, 'Philip': 2, 'Frank': 6, 'Victor': 3, 'Rod': 2, 'Lewis': 1, 'Walter': 3, 'Henry': 2, 'Phil': 2, 'Tim': 3, 'Tom': 2, 'Bob': 9, 'Rick': 4, 'Ron': 3, 'Steven': 3, 'Bill': 2, 'Don': 1, 'Ken': 2, 'Lincoln': 3, 'Gary': 2, 'Jon': 3, 'Greg': 1, 'Tony': 1, 'Brian': 3, 'Steve': 4, 'Dan': 2, 'Joe': 4, 'Dean': 1, 'Aníbal': 1, 'Wayne': 2, 'Chris': 2, 'Max': 3, 'Brad': 2, 'Norm': 1, 'Larry': 3, 'Calvin': 1, 'Ernest': 2, 'Jonas': 1, 'Christopher': 6, 'Gerald': 2, 'Scott': 3, 'Doug': 1, 'Jack': 1, 'Gordon': 1, 'Evan': 1, 'Jeb': 1, 'Ed': 1, 'C.': 1, 'Randall': 1, 'Byron': 1, 'Lane': 1, 'Russell': 1, 'Judd': 1, 'Gilbert': 1, 'Mel': 1, 'C.L.': 1, 'Jim': 3, 'Ted': 1, 'W.': 2, 'Rahm': 1, 'Luis': 1, 'Vito': 1, 'Virgil': 1, 'J.': 1, 'Robin': 1, 'Kenny': 1, 'Duncan': 1, 'Bobby': 2, 'Ric': 1, 'Ray': 1, 'Nicholas': 1, 'Trent': 1, 'H.': 1, 'Allen': 2, 'Stephen': 1, 'Anh': 1, 'Travis': 1, 'Artur': 1, 'Nathan': 1, 'Barton': 1, 'Parker': 1, 'Baron': 1, 'Eric': 2, 'Kendrick': 1, 'Alan': 1, 'Dennis': 4, 'Glenn': 1, 'Adam': 1, 'Ciro': 1, 'Zachary': 1, 'Bart': 1, 'Gene': 1, 'Todd': 2, 'Zach': 1, 'Carte': 1, 'Geoff': 1, 'Jay': 1, 'Thaddeus': 1, 'Jesse': 1, 'Barack': 1, 'Jeff': 2, 'Kent': 1, 'Ben': 3, 'Jason': 1, 'Howard': 1, 'Francisco': 1, 'Russ': 1, 'Hansen': 1, 'Jerry': 1, 'Chip': 1, 'Elton': 1, 'Connie': 1, 'R.': 1, 'Mike': 2, 'Silvestre': 1, 'Heath': 1, 'Clifford': 1, 'Jo': 1, 'Rodney': 1, 'Jeffrey': 1, 'Melvin': 1, 'Trey': 1}

In [27]:
top_male_count = None

for name, count in male_name_counts.items():
    if top_male_count is None or count > top_male_count:
        top_male_count = count

print(top_male_count)

35

In [28]:
top_male_names = []

for name, count in male_name_counts.items():
    if count == top_male_count:
        top_male_names.append(name)
        
print(top_male_names)

['John']