# La compr√©hension de liste

## Fonction enumerate()

In [1]:
students = ["Anna", "Martin", "Bob", "Eric", "Elise"]
ages = [16, 15, 18, 20, 20]

In [2]:
for student in students:
    print("Etudiant")
    print(student)
    print("Age")

Etudiant
Anna
Age
Etudiant
Martin
Age
Etudiant
Bob
Age
Etudiant
Eric
Age
Etudiant
Elise
Age

In [3]:
for i, student in enumerate(students):
    print("Index Etudiant")
    print(i)
    print("Etudiant")
    print(student)

Index Etudiant
0
Etudiant
Anna
Index Etudiant
1
Etudiant
Martin
Index Etudiant
2
Etudiant
Bob
Index Etudiant
3
Etudiant
Eric
Index Etudiant
4
Etudiant
Elise

In [4]:
for i, student in enumerate(students):
    print("Index Etudiant")
    print(i)
    print("Etudiant")
    print(student)
    print("Age")
    print(ages[i])

Index Etudiant
0
Etudiant
Anna
Age
16
Index Etudiant
1
Etudiant
Martin
Age
15
Index Etudiant
2
Etudiant
Bob
Age
18
Index Etudiant
3
Etudiant
Eric
Age
20
Index Etudiant
4
Etudiant
Elise
Age
20

In [5]:
cars = [["Noir", "Peugeot", "308"], ["Blanche", "Audi", "A4"]]
price = [23000, 49000]

In [7]:
for i, car in enumerate(cars):
    car.append(price[i])

In [8]:
print(cars)

[['Noir', 'Peugeot', '308', 23000], ['Blanche', 'Audi', 'A4', 49000]]